version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: appsforbharat12345
      MYSQL_DATABASE: appsforbharat
      MYSQL_USER: afbuser
      MYSQL_PASSWORD: appsforbharat12345

  redis:
    image: redis:latest
    restart: always

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "678:678"
    depends_on:
      - mysql
      - redis
